# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id_developer', models.AutoField(primary_key=True, serialize=False)),
                ('developer_name', models.CharField(max_length=40)),
                ('developer_age', models.CharField(max_length=100)),
                ('bool_developer', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id_game', models.AutoField(primary_key=True, serialize=False)),
                ('game_name', models.CharField(max_length=50)),
                ('game_year', models.CharField(max_length=20)),
                ('publisher', models.CharField(max_length=20)),
                ('game_cover', models.CharField(max_length=1000)),
                ('bool_game', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id_genre', models.AutoField(primary_key=True, serialize=False)),
                ('genre_type', models.CharField(max_length=100)),
                ('bool_genre', models.BooleanField()),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='game_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Genre'),
        ),
        migrations.AddField(
            model_name='developer',
            name='developer_game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.Game'),
        ),
    ]
