# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-29 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='developer_age',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_cover',
        ),
    ]
